import sqlite3
conn = sqlite3.connect('database/overseer_trades.db')
c = conn.cursor()
c.execute("SELECT MIN(tick_bid), MAX(tick_bid), AVG(tick_bid), MIN(tick_ask), MAX(tick_ask) FROM signal_log WHERE symbol='6JM6' AND outcome_200ticks='WIN'")
r = c.fetchone()
print(f"6JM6 WIN signals: bid=[{r[0]}, {r[1]}] avg={r[2]} ask=[{r[3]}, {r[4]}]")
c.execute("SELECT MIN(tick_bid), MAX(tick_bid), AVG(tick_bid) FROM signal_log WHERE symbol='6EM6' AND outcome_200ticks='WIN'")
r = c.fetchone()
print(f"6EM6 WIN signals: bid=[{r[0]}, {r[1]}] avg={r[2]}")
c.execute("SELECT MIN(tick_bid), MAX(tick_bid), AVG(tick_bid) FROM signal_log WHERE symbol='6CM6' AND outcome_200ticks='WIN'")
r = c.fetchone()
print(f"6CM6 WIN signals: bid=[{r[0]}, {r[1]}] avg={r[2]}")
conn.close()
