@echo off
REM Start the CQG WebAPI -> OVERSEER ZMQ bridge.
REM Credentials are read from overseer\.env (do not edit this file with secrets).
cd /d "%~dp0\.."
.venv\Scripts\python.exe tools\cqg_mbo_bridge.py
pause
