export const MAX_CANDLES = 8192;
export const MAX_PRICE_LEVELS = 4096;
export const CANDLE_PRICE_LEVELS = 64;
export const SAB_SIZE = 512 * 1024 * 1024;
export const HEADER_SIZE = 128;
export const SLOT_SIZE = 128;
export const SLOT_COUNT = Math.floor((SAB_SIZE - HEADER_SIZE) / SLOT_SIZE);
export const CACHE_LINE_SIZE = 64;

export const CONTROL = Object.freeze({
  WRITE_INDEX: 0,
  READ_INDEX: 4,
  BUFFER_CAPACITY: 8,
  PRODUCER_EPOCH: 12,
  CONSUMER_EPOCH: 16,
  FLAGS: 20,
  TICK_COUNT: 24,
  PAD_START: 32,
});

export const SLOT = Object.freeze({
  TIMESTAMP_NS: 0,
  PRICE: 8,
  BID_SIZE: 16,
  ASK_SIZE: 24,
  TRADE_SIZE: 32,
  ORDER_ID: 40,
  FLAGS: 44,
  PRICE_LEVEL_IDX: 48,
  CANDLE_IDX: 52,
  SEQ_NUM: 56,
  ACTION: 60,
  SIDE: 61,
  RESERVED_START: 62,
});

export const FLAG_IS_BID = 1 << 0;
export const FLAG_IS_TRADE = 1 << 1;
export const FLAG_IS_ICEBERG = 1 << 2;
export const FLAG_IS_ABSORPTION = 1 << 3;
export const FLAG_IS_LIQUIDATION = 1 << 4;
export const FLAG_IS_SNAPSHOT = 1 << 5;

export const ACTION = Object.freeze({
  INSERT: 0,
  UPDATE: 1,
  DELETE: 2,
  TRADE: 3,
  TOP_OF_BOOK: 4,
});

export const SIDE = Object.freeze({
  BID: 0,
  ASK: 1,
});

export const FEATURE_SAB_SIZE = 128 * 1024 * 1024;

const _8K = 8 * 8192;
const _4K = 4 * 4096;
const _1K = 1 * 4096;
const _ICE = 4 * 65536;
const _BBO = 8 * 216000;
const _TPO = 4 * 4096 * 96;
const _CPL = 4 * 8192 * CANDLE_PRICE_LEVELS;

let _off = 256;
_off += _8K;
const CVD_OFF = _off - _8K;
_off += _8K;
const DELTA_OFF = _off - _8K;
_off += _4K;
const IMB_OFF = _off - _4K;
_off += _1K;
const STK_OFF = _off - _1K;
_off += _8K;
const VPOC_OFF = _off - _8K;
_off += 8 * 4096;
const VPROF_OFF = _off - 8 * 4096;
_off += _TPO;
const TPO_OFF = _off - _TPO;
_off += _ICE;
const ICE_OFF = _off - _ICE;
_off += _1K;
const ABS_OFF = _off - _1K;
_off += _BBO;
const BBO_BID_OFF = _off - _BBO;
_off += _BBO;
const BBO_ASK_OFF = _off - _BBO;
_off += _8K;
const MAX_D_OFF = _off - _8K;
_off += _8K;
const MIN_D_OFF = _off - _8K;
_off += _8K;
const TOT_VOL_OFF = _off - _8K;
_off += _1K;
const DIV_OFF = _off - _1K;
_off += _CPL;
const CBID_OFF = _off - _CPL;
_off += _CPL;
const CASK_OFF = _off - _CPL;
_off += 8 * 4096;
const LOB_BID_OFF = _off - 8 * 4096;
_off += 8 * 4096;
const LOB_ASK_OFF = _off - 8 * 4096;

_off += _8K;
const OHLC_OPEN_OFF = _off - _8K;
_off += _8K;
const OHLC_HIGH_OFF = _off - _8K;
_off += _8K;
const OHLC_LOW_OFF = _off - _8K;
_off += _8K;
const OHLC_CLOSE_OFF = _off - _8K;

_off += 16;
const SESSION_VWAP_OFF = _off - 16;
_off += 16;
const BUY_VWAP_OFF = _off - 16;
_off += 16;
const SELL_VWAP_OFF = _off - 16;

_off += 8 * 2;
const IBR_OFF = _off - 8 * 2;
_off += _1K;
const SINGLE_PRINTS_OFF = _off - _1K;
_off += 8;
const BUYING_TAIL_OFF = _off - 8;
_off += 8;
const SELLING_TAIL_OFF = _off - 8;
_off += 8;
const NAKED_POC_OFF = _off - 8;

_off += _1K;
const EXHAUSTION_OFF = _off - _1K;
_off += _1K;
const SWEEP_FLAGS_OFF = _off - _1K;

const _OFT_RATIO = 1 * 8192 * 64;
_off += _OFT_RATIO;
const OFT_RATIO_OFF = _off - _OFT_RATIO;
_off += _1K;
const OFT_SLINGSHOT_OFF = _off - _1K;
_off += _1K;
const OFT_WEAKNESS_OFF = _off - _1K;
_off += _1K;
const OFT_SEQUENCING_OFF = _off - _1K;

export const FEATURE = Object.freeze({
  HEADER_SIZE: 256,
  CVD_OFFSET: CVD_OFF,
  CVD_SIZE: _8K,
  DELTA_OFFSET: DELTA_OFF,
  DELTA_SIZE: _8K,
  IMBALANCE_MAP_OFFSET: IMB_OFF,
  IMBALANCE_MAP_SIZE: _4K,
  STACKED_IMBALANCE_OFFSET: STK_OFF,
  STACKED_IMBALANCE_SIZE: _1K,
  VPOC_OFFSET: VPOC_OFF,
  VPOC_SIZE: _8K,
  VOLUME_PROFILE_OFFSET: VPROF_OFF,
  VOLUME_PROFILE_SIZE: 8 * 4096,
  TPO_MAP_OFFSET: TPO_OFF,
  TPO_MAP_SIZE: _TPO,
  ICEBERG_MAP_OFFSET: ICE_OFF,
  ICEBERG_MAP_SIZE: _ICE,
  ABSORPTION_FLAGS_OFFSET: ABS_OFF,
  ABSORPTION_FLAGS_SIZE: _1K,
  BBO_BID_OFFSET: BBO_BID_OFF,
  BBO_BID_SIZE: _BBO,
  BBO_ASK_OFFSET: BBO_ASK_OFF,
  BBO_ASK_SIZE: _BBO,
  MAX_DELTA_OFFSET: MAX_D_OFF,
  MAX_DELTA_SIZE: _8K,
  MIN_DELTA_OFFSET: MIN_D_OFF,
  MIN_DELTA_SIZE: _8K,
  TOTAL_VOLUME_OFFSET: TOT_VOL_OFF,
  TOTAL_VOLUME_SIZE: _8K,
  DIVERGENCE_OFFSET: DIV_OFF,
  DIVERGENCE_SIZE: _1K,
  CANDLE_BID_VOL_OFFSET: CBID_OFF,
  CANDLE_BID_VOL_SIZE: _CPL,
  CANDLE_ASK_VOL_OFFSET: CASK_OFF,
  CANDLE_ASK_VOL_SIZE: _CPL,
  LOB_BID_DEPTH_OFFSET: LOB_BID_OFF,
  LOB_BID_DEPTH_SIZE: 8 * 4096,
  LOB_ASK_DEPTH_OFFSET: LOB_ASK_OFF,
  LOB_ASK_DEPTH_SIZE: 8 * 4096,
  OHLC_OPEN_OFFSET: OHLC_OPEN_OFF,
  OHLC_OPEN_SIZE: _8K,
  OHLC_HIGH_OFFSET: OHLC_HIGH_OFF,
  OHLC_HIGH_SIZE: _8K,
  OHLC_LOW_OFFSET: OHLC_LOW_OFF,
  OHLC_LOW_SIZE: _8K,
  OHLC_CLOSE_OFFSET: OHLC_CLOSE_OFF,
  OHLC_CLOSE_SIZE: _8K,
  SESSION_VWAP_OFFSET: SESSION_VWAP_OFF,
  SESSION_VWAP_SIZE: 16,
  BUY_VWAP_OFFSET: BUY_VWAP_OFF,
  BUY_VWAP_SIZE: 16,
  SELL_VWAP_OFFSET: SELL_VWAP_OFF,
  SELL_VWAP_SIZE: 16,
  IBR_HIGH_OFFSET: IBR_OFF,
  IBR_LOW_OFFSET: IBR_OFF + 8,
  IBR_SIZE: 8 * 2,
  SINGLE_PRINTS_OFFSET: SINGLE_PRINTS_OFF,
  SINGLE_PRINTS_SIZE: _1K,
  BUYING_TAIL_OFFSET: BUYING_TAIL_OFF,
  BUYING_TAIL_SIZE: 8,
  SELLING_TAIL_OFFSET: SELLING_TAIL_OFF,
  SELLING_TAIL_SIZE: 8,
  NAKED_POC_OFFSET: NAKED_POC_OFF,
  NAKED_POC_SIZE: 8,
  EXHAUSTION_OFFSET: EXHAUSTION_OFF,
  EXHAUSTION_SIZE: _1K,
  SWEEP_FLAGS_OFFSET: SWEEP_FLAGS_OFF,
  SWEEP_FLAGS_SIZE: _1K,
  OFT_RATIO_OFFSET: OFT_RATIO_OFF,
  OFT_RATIO_SIZE: _OFT_RATIO,
  OFT_SLINGSHOT_OFFSET: OFT_SLINGSHOT_OFF,
  OFT_SLINGSHOT_SIZE: _1K,
  OFT_WEAKNESS_OFFSET: OFT_WEAKNESS_OFF,
  OFT_WEAKNESS_SIZE: _1K,
  OFT_SEQUENCING_OFFSET: OFT_SEQUENCING_OFF,
  OFT_SEQUENCING_SIZE: _1K,
  CURRENT_CANDLE_IDX: 0,
  CURRENT_SLOT: 4,
  ALGO_WRITE_EPOCH: 8,
  CANDLE_COUNT: 12,
  CANDLE_PRICE_LEVELS: CANDLE_PRICE_LEVELS,
});

export const FEATURE_HEADER = Object.freeze({
  CURRENT_CANDLE_IDX: 0,
  CURRENT_SLOT: 4,
  ALGO_WRITE_EPOCH: 8,
  CANDLE_COUNT: 12,
  TPO_SLOT_IDX: 16,
  SESSION_START_NS: 24,
  BID_COUNT: 28,
  ASK_COUNT: 32,
});
